---
- name: Remove old docker packages if any
  yum:
    state: absent
    name: "{{ item }}"
  become: True
  become_method: sudo
  with_items: "{{ clean_up_old_docker_packages }}"
- name: Install required packages
  yum:
    state: present
    name: "{{ item }}"
  become: True
  become_method: sudo
  with_items: "{{ required_packages }}"
- name: Import Docker CE repository gpg key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present
  become: True
  become_method: sudo
- name: Add Docker CE repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    force: yes
    owner: root
    group: root
    mode: 0644
  become: True
  become_method: sudo
- name: Install Docker CE
  yum:
    name: docker-ce
    state: present
    update_cache: yes
  become: True
  become_method: sudo
- name: Start docker machine
  systemd:
    name: docker
    state: started
    enabled: True
  become: True
  become_method: sudo
